### ISSUE TITLE
Latest fails to build

### ISSUE THREAD

**Issue by cryptoquick** [rust-bitcoin/rust-bitcoin#3171] opened 2024-08-15 11:03 UTC
Hi, I just started a new project and immediately hit a rust-bitcoin snag. In trying to debug the snag, I wanted to use the very latest rust-bitcoin to see if changes needed to be made, but I can't get it to compile.

You can find the simple minimal concept here:
https://github.com/SurmountSystems/gabriel/blob/9c42e457c4a7d0d85546c65334b19745a9b9b0c3/src/main.rs

After [patching the crates to also use the crates from master](https://github.com/SurmountSystems/gabriel/blob/9c42e457c4a7d0d85546c65334b19745a9b9b0c3/Cargo.toml), I ran into this error, and I'm not quite sure what to do:

```
   Compiling openssl-sys v0.9.103
   Compiling secp256k1-sys v0.10.0
   Compiling bitcoin-primitives v0.100.0 (/home/hunter/Projects/bitcoin/rust-bitcoin/primitives)
error[E0432]: unresolved imports `units::parse::PrefixedHexError`, `units::parse::UnprefixedHexError`
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/locktime/absolute.rs:13:26
   |
13 | use units::parse::{self, PrefixedHexError, UnprefixedHexError};
   |                          ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^ no `UnprefixedHexError` in `parse`
   |                          |
   |                          no `PrefixedHexError` in `parse`

error[E0432]: unresolved imports `units::parse::PrefixedHexError`, `units::parse::UnprefixedHexError`
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/sequence.rs:25:26
   |
25 | use units::parse::{self, PrefixedHexError, UnprefixedHexError};
   |                          ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^ no `UnprefixedHexError` in `parse`
   |                          |
   |                          no `PrefixedHexError` in `parse`

error[E0425]: cannot find function `hex_u32_prefixed` in module `parse`
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/locktime/absolute.rs:95:32
   |
95 |         let lock_time = parse::hex_u32_prefixed(s)?;
   |                                ^^^^^^^^^^^^^^^^ not found in `parse`

error[E0425]: cannot find function `hex_u32_unprefixed` in module `parse`
   --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/locktime/absolute.rs:101:32
    |
101 |         let lock_time = parse::hex_u32_unprefixed(s)?;
    |                                ^^^^^^^^^^^^^^^^^^ not found in `parse`

error[E0425]: cannot find function `hex_u32_prefixed` in module `parse`
   --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/sequence.rs:121:32
    |
121 |         let lock_time = parse::hex_u32_prefixed(s)?;
    |                                ^^^^^^^^^^^^^^^^ not found in `parse`

error[E0425]: cannot find function `hex_u32_unprefixed` in module `parse`
   --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/sequence.rs:128:32
    |
128 |         let lock_time = parse::hex_u32_unprefixed(s)?;
    |                                ^^^^^^^^^^^^^^^^^^ not found in `parse`

warning: private item shadows public glob re-export
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/lib.rs:29:1
   |
29 | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
   |
note: the name `serde` in the type namespace is supposed to be publicly re-exported here
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/lib.rs:37:9
   |
37 | pub use units::*;
   |         ^^^^^^^^
note: but the private item here shadows it
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/lib.rs:29:1
   |
29 | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
   = note: `#[warn(hidden_glob_reexports)]` on by default

   Compiling secp256k1 v0.29.0
Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
warning: `bitcoin-primitives` (lib) generated 1 warning
error: could not compile `bitcoin-primitives` (lib) due to 6 previous errors; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
```

**Comment by apoelstra** [comment] 2024-08-15 13:34
This may be fixed by https://github.com/rust-bitcoin/rust-bitcoin/pull/2861

**Comment by cryptoquick** [comment] 2024-08-15 22:02
Hmm... I'll try his changes out.
So what I did was, in parent `rust-bitcoin`:
```
git remote add tcharding https://github.com/tcharding/rust-bitcoin.git
git fetch tcharding
git checkout -b review-branch tcharding/06-12-impl_bytelike_traits
```
I then tried running with `ONION='xyz' cargo run` and I still got the same error. I think it's the same error.

```
   Compiling base58ck v0.1.0 (/home/hunter/Projects/bitcoin/rust-bitcoin/base58)
   Compiling secp256k1 v0.29.0
   Compiling bitcoin-primitives v0.100.0 (/home/hunter/Projects/bitcoin/rust-bitcoin/primitives)
error[E0432]: unresolved imports `units::parse::PrefixedHexError`, `units::parse::UnprefixedHexError`
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/locktime/absolute.rs:13:26
   |
13 | use units::parse::{self, PrefixedHexError, UnprefixedHexError};
   |                          ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^ no `UnprefixedHexError` in `parse`
   |                          |
   |                          no `PrefixedHexError` in `parse`

error[E0432]: unresolved imports `units::parse::PrefixedHexError`, `units::parse::UnprefixedHexError`
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/sequence.rs:25:26
   |
25 | use units::parse::{self, PrefixedHexError, UnprefixedHexError};
   |                          ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^ no `UnprefixedHexError` in `parse`
   |                          |
   |                          no `PrefixedHexError` in `parse`

error[E0425]: cannot find function `hex_u32_prefixed` in module `parse`
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/locktime/absolute.rs:95:32
   |
95 |         let lock_time = parse::hex_u32_prefixed(s)?;
   |                                ^^^^^^^^^^^^^^^^ not found in `parse`

error[E0425]: cannot find function `hex_u32_unprefixed` in module `parse`
   --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/locktime/absolute.rs:101:32
    |
101 |         let lock_time = parse::hex_u32_unprefixed(s)?;
    |                                ^^^^^^^^^^^^^^^^^^ not found in `parse`

error[E0425]: cannot find function `hex_u32_prefixed` in module `parse`
   --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/sequence.rs:121:32
    |
121 |         let lock_time = parse::hex_u32_prefixed(s)?;
    |                                ^^^^^^^^^^^^^^^^ not found in `parse`

error[E0425]: cannot find function `hex_u32_unprefixed` in module `parse`
   --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/sequence.rs:128:32
    |
128 |         let lock_time = parse::hex_u32_unprefixed(s)?;
    |                                ^^^^^^^^^^^^^^^^^^ not found in `parse`

warning: private item shadows public glob re-export
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/lib.rs:29:1
   |
29 | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
   |
note: the name `serde` in the type namespace is supposed to be publicly re-exported here
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/lib.rs:37:9
   |
37 | pub use units::*;
   |         ^^^^^^^^
note: but the private item here shadows it
  --> /home/hunter/Projects/bitcoin/rust-bitcoin/primitives/src/lib.rs:29:1
   |
29 | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
   = note: `#[warn(hidden_glob_reexports)]` on by default

Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
warning: `bitcoin-primitives` (lib) generated 1 warning
error: could not compile `bitcoin-primitives` (lib) due to 6 previous errors; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
```

**Comment by apoelstra** [comment] 2024-08-15 22:11
What target did you use with `cargo run`?

**Comment by cryptoquick** [comment] 2024-08-15 22:31
@apoelstra Just the default... I can give you my default target triple:
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7

Looks like I need to update my Rust version...

**Comment by cryptoquick** [comment] 2024-08-15 22:33
Yes, even after updating to the latest:

`stable-x86_64-unknown-linux-gnu updated - rustc 1.80.1 (3f5fd8dd4 2024-08-06) (from rustc 1.79.0 (129f3b996 2024-06-10))`

I still get the same error.

**Comment by apoelstra** [comment] 2024-08-15 22:41
There is no default. When I do `cargo run` I get the error

```
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifestkey.
available binaries: bitcoin_deser_net_msg, bitcoin_deserialize_address, bitcoin_deserialize_block, bitcoin_deserialize_prefilled_transaction, bitcoin_deserialize_psbt, bitcoin_deserialize_script, bitcoin_deserialize_transaction, bitcoin_deserialize_witness, bitcoin_outpoint_string, bitcoin_script_bytes_to_asm_fmt, hashes_json, hashes_ripemd160, hashes_sha1, hashes_sha256, hashes_sha512, hashes_sha512_256, units_deserialize_amount
```

**Comment by cryptoquick** [comment] 2024-08-15 23:51
Strange! I don't see that on my end, and what's also interesting is that there's all these available binaries that have nothing to do with my code.

Can you try `cargo run --bin gabriel` ? This is against a mempool server API. Not sure if there are many differences between that and the Bitcoin Core REST API.

**Comment by apoelstra** [comment] 2024-08-16 13:01
Thanks! Can reproduce now. I was running in the wrong directory. I took your code and changed all the patch paths and now I see the same errors as you.

**Comment by apoelstra** [comment] 2024-08-16 13:16
The issue is that the patch is not being used by `units`. Your lockfile has `units` set to 0.1.2 but the version in master's Cargo.toml is 0.1.1.

I guess we should fix that on our end, but it's technically "working as intended". Or at least, it's a bug in cargo rather than a bug here.

**Comment by yancyribbens** [comment] 2024-08-16 15:10
I also had trouble with this recently.  Managed to get it to compile by using `path = "../units"` as a hack for now.

**Closed** 2024-08-26 21:20 UTC
