### ISSUE TITLE
Serialized transaction with no inputs not accepted by `fundrawtransation`

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#2295] opened 2023-12-16 11:01 UTC
Passing a serialized transaction with no inputs to `bitcoin-cli fundrawtransaction` fails with the error message `TX decode failed`.

I thought that this probably had to do with pre and post BIP 141 serialization, but passing either `true` or `false` as the `iswitness` argument to `fundrawtransaction` didn't seem to make a difference.

Here is code to reproduce the error:

```rust
use {
    bitcoin::{
        absolute::LockTime, consensus::encode::serialize, transaction::Version, Amount, ScriptBuf,
        Transaction, TxOut,
    },
    std::process::Command,
};

fn main() {
    let unfunded_transaction = Transaction {
        version: Version(1),
        lock_time: LockTime::ZERO,
        input: Vec::new(),
        output: vec![TxOut {
            script_pubkey: ScriptBuf::new(),
            value: Amount::from_sat(1000),
        }],
    };

    let hex = hex::encode(serialize(&unfunded_transaction));

    let status = Command::new("bitcoin-cli")
        .arg("--regtest")
        .arg("fundrawtransaction")
        .arg(hex)
        .arg("{}")
        .arg("true")
        .status()
        .unwrap();

    if !status.success() {
        panic!("{status}");
    }
}
```

**Comment by Kixunil** [comment] 2023-12-16 13:51
This is fundamentally a dupe of #2238 where we decided this is not supported and you should use PSBT instead.

**Closed by Kixunil** 2023-12-16 13:51 UTC

**Comment by casey** [comment] 2023-12-17 11:27
Got it, thank you!
