### ISSUE TITLE
Segwit Address struct allows constructing invalid Address

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1561] opened 2023-01-19 13:48 UTC
Both `Address::from_str` and `Address::from_script` check constraints witness programs (len between 2 and 40 and others). But it is possible to directly construct the `Address` struct as all its member fields (`Payload` in particular) are public. 

We should make internal fields of  `Address` private and a make failing constructor that checks the invariants.

**Comment by Kixunil** [comment] 2023-01-19 16:23
I think this is essentially a duplicate of #648 and I agree with the proposal.

**Closed** 2023-01-24 13:25 UTC
Labels: bug
