### ISSUE TITLE
Proposal: split rust-bitcoin into workspace with multiple crates

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#549] opened 2021-01-13 16:41 UTC
I propose we split some parts of rust-bitcoin into multiple crates:
* `bitcoin-encoding` which has all the string encodings that bitcoin uses: base58, base58check, bech32, bech32m, base64, hex
  * this would collapse `base64_compat`, `bech32-bitcoin`, `byteorder` all into one dep that we control. maybe also `bech32`.
  * would also let us write a unified interface to all these
  * potentially could be a dep of rust-secp, letting us encode keys and base64 signatures the way users expect
  * lets us deal with the unique no_std difficulties around string encoding in one place
* `bitcoin-primitives` which defines block/transaction/script, and the p2p messages, and the consensus::Encodable trait
  * lets users parse/serialize bitcoin stuff without needing rust-secp and the rest of the massive dep tree. see e.g. #527 
  * similar benefits to the above wrt no_std, lets us deal with `Vec` encoding and use of `io::Write` in one place
* `bitcoin-keys` which deals with private/public keys, addresses, bech32, taproot, as well as computing sighashes. I think this is the only one that'd require a rust-secp dependency
* `bitcoin-psbt`

I think this covers all the contents of the library. Then the main "bitcoin" crate would simply have optional deps on all of the above and re-export everything from them.

**Comment by dr-orlovsky** [comment] 2021-01-13 17:27
What is the difference with #550?

**Comment by Kixunil** [comment] 2021-01-13 17:30
Looks like double-post presumably caused by GitHub glitches lately? I've experienced it two or three times lately - got 404 after sending an issue and almost posted it again but noticed it was actually posted. GitHub should rewrite their backend into Rust to avoid such races. :rofl: :rofl: 

I suggest to close this one since the technical discussion already started at the other one.

**Closed** 2021-01-13 17:38 UTC
