### ISSUE TITLE
Add `#[cfg_attr(docsrs, doc(notable_trait))]` to extension traits

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3218] opened 2024-08-22 10:17 UTC
See https://doc.rust-lang.org/stable/unstable-book/language-features/doc-notable-trait.html

Just adding the attribute in the macro for all of them makes sense.

**Comment by tcharding** [comment] 2024-10-30 05:04
Duplicate of #3232

**Closed by tcharding** 2024-10-30 05:04 UTC
