### ISSUE TITLE
`non_exhaustive` attribute considered harmful

### ISSUE THREAD

**Issue by adoerr** [rust-bitcoin/rust-bitcoin#1930] opened 2023-07-04 05:00 UTC
I do understand the usefulness of the `non_exhaustive` attribute for maintaining backwards compatibility **if** a type is likely to be changed or extended often. 

However, the `non_exhaustive` attribute also imposes quite noticeable restrictions. The arguably most pervasive restriction being that matching on a `non_exhaustive` value requires a match arm with a wildcard pattern in a downstream create.

The [Remove user_enum macro](https://github.com/rust-bitcoin/rust-bitcoin/pull/1291l) PR introduced the `non_exhaustive` attribute to the [Network](https://github.com/rust-bitcoin/rust-bitcoin/blob/83cf389a02d6147a4cd3fe9c42388c61abd40ec2/bitcoin/src/network/constants.rs#L67-L68) enum.

This requires a downstream crate to match on a network wildcard, which, IMO, is a bit disturbing. I would also argue that adding support for a new network type **should** be a breaking change.

**Comment by dpc** [comment] 2023-07-04 07:38
For anything else than Bitcoin node itself that needs to join right p2p network, there should have ever been just two networks: mainnet and testnet (everything that isn't real Bitcoin). There is no reason to worry about people confusing networks of worthless testnet coins/addresses.

Bitcoin Core could still abandon this pointless source of headaches, and first commit to only using one network for all future networks, then retroactively change/phase out networks that are using extra network ids. 


> I would also argue that adding support for a new network type should be a breaking change.

Fracture the whole ecosystem just because of that? Meh. 

> This requires a downstream crate to match on a network wildcard, which, IMO, is a bit disturbing.

This is meh as well, but much smaller meh, IMO, and in projects where it's really inconvenient, can probably be easily macroized.

**Comment by adoerr** [comment] 2023-07-04 13:04
> > This requires a downstream crate to match on a network wildcard, which, IMO, is a bit disturbing. I would also argue that adding support for a new network type **should** be a breaking change.
> 
> Why? If we have testnet4 or whatever I can't see why any existing code should remotely care about this.

That is certainly a valid point and that is why I'm not against non exhaustive enums in general.

With the `Network` enum in particular, my issue is that new networks are added at a fairly low frequency while every single user has to deal with the wildcard match arm every time it is trying to match on `Network`.

I agree that it is certainly not obvious how to balance the respective disadvantages here.

**Comment by tcharding** [comment] 2024-01-24 04:44
Duplicate of the discussion over in #2225

**Closed by tcharding** 2024-01-24 04:44 UTC
