### ISSUE TITLE
Consider feature-gating `secp256k1`

### ISSUE THREAD

**Issue by alfred-hodler** [rust-bitcoin/rust-bitcoin#2799] opened 2024-05-24 00:37 UTC
There are times when EC operations aren't needed and `rust-bitcoin` is being used just for its data types and consensus encode/decode capabilities.

The reason why indiscriminately including `secp256k1` into the build can be problematic is because Rust's FFI doesn't allow more than one version of the same C lib to be included in the dependency tree. This becomes a problem when different dependencies want  `rust-bitcoin` versions that have incompatible `secp256k1` versions.

**Comment by tcharding** [comment] 2024-05-24 02:08
This is something we are working on ATM, in https://github.com/rust-bitcoin/rust-bitcoin/pull/2756 we add a "crypto" feature that feature gates `libsec256k1`. Of note we basically thought that there would be no users of it because it strips out so much (all key types and signatures). If you have time could you take a read of the PR description and let us know if you are likely to be able to use the new `primitives` crate without the "crypto" feature enabled? Thanks for raising the issue>

**Comment by apoelstra** [comment] 2024-05-24 13:29
Closing as dupe of #526. But as @tcharding says, we do take this issue seriously and are working toward fixing it. It's just hard with the current architecture of the library (see discussion in that issue).

**Closed by apoelstra** 2024-05-24 13:29 UTC
