### ISSUE TITLE
Do We require  BIP324 implementation?

### ISSUE THREAD

**Issue by 15IITian** [rust-bitcoin/rust-bitcoin#2672] opened 2024-04-08 04:31 UTC
Well , I  have no idea of  whether we require BIP324  implementation in rust-bitcoin .
If so ,  @rustaceanrob has implemented this in rust https://github.com/rustaceanrob/bip324  , from which we can either take reference or directly  incorporate it in our codebase .

**Comment by tcharding** [comment] 2024-04-08 05:37
This is a duplicate of https://github.com/rust-bitcoin/rust-bitcoin/discussions/1691

**Closed by tcharding** 2024-04-08 05:37 UTC
