### ISSUE TITLE
Not-really-monorepo trouble

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1553] opened 2023-01-14 20:24 UTC
It appeared that by merging `bitcoin_hashes` and patching we could do changes into multiple crates. Unfortunately, this doesn't include `secp256k` which forms a "hole" in our crate tree, so everything breaks when we need to do a breaking change to `bitcoin_hashes`.

This cannot be easily fixed by using git dependencies and/or having a separate branch because we need to merge `rust-bitcoin` before `secp256k1` can compile but we can't compile `rust-bitcoin` before `secp256k1` is merged. Perhaps the only solution, apart from merging these repositories too, is to have a temporary branch that doesn't require tests to pass.

Any other ideas?

Note: setting P-high because this blocks development, specifically #1481

**Comment by apoelstra** [comment] 2023-01-14 20:33
Hmmm. This is pretty frustrating. I really don't want to merge the repos because rust-secp has a different maintainer set, is far far lower volume, and the work on rust-secp is "of a different nature" than work here. (It seems like 95% of what we do on rust-secp is deal with weird C crap, alignment issues and synchronization and FFI, all of which we avoid in rust-bitcoin).

In many cases, it should be possible to semver-trick bitcoin_hashes so that whenever we do breaking changes to its API, rust-secp's (now outdated) version continues to work.

**Comment by Kixunil** [comment] 2023-01-14 20:36
Sadly, I don't think semver trick works in case of #1481 :(

**Comment by apoelstra** [comment] 2023-01-14 20:37
Then yes, I think we'll have to deal with some short-term breakage. If we can keep the breakage on a non-`master` branch of rust-bitcoin that'd be great, though I'm not sure that we can.

**Comment by Kixunil** [comment] 2023-01-14 20:48
I think we need to depend on `bitcoin_hashes` with git dep and a commit in the past first, then merge secp256k1 PR that depends on the new `bitcoin_hashes` and finally another PR that depends on the new `bitcoin_hashes` and new secp256k1.

**Comment by sanket1729** [comment] 2023-01-14 21:26
> I think we need to depend on bitcoin_hashes with git dep and a commit in the past first, then merge secp256k1 PR that depends on the new bitcoin_hashes and finally another PR that depends on the new bitcoin_hashes and new secp256k1.

We need to always do that whenever we have a breaking change? Perhaps we can have `rust-secp256k1` have a git dependency as `master` of `bitcoin_hashes`. Whenever we make a release, we would need to remember to update to a fixed version. 

Perhaps, it's really not a mono-repo. Even if we have the code in the single repo, we should be using crates releases instead of a patch with path.

**Comment by Kixunil** [comment] 2023-01-14 21:43
`bitcoin_hashes` is no longer a separate repo, that's why we have this problem.

**Comment by sanket1729** [comment] 2023-01-14 22:32
Perhaps, I am not explaining clearly. I am suggesting, 
```diff
-bitcoin_hashes = { version = "0.11", default-features = false, optional = true }
+bitcoin_hashes = { git = "https://github.com/rust-bitcoin/rust-bitcoin", branch = "master", default-features = false, optional = true }
```

This works, and I tested it with rust-secp256k1. The only catch is that when releasing we need to release a fixed release of `bitcoin_hashes`.

**Comment by sanket1729** [comment] 2023-01-14 22:33
This works because 
> Cargo will fetch the git repository at this location then look for a Cargo.toml for the requested crate anywhere inside the git repository (not necessarily at the root - for example, specifying a member crate name of a workspace and setting git to the repository containing the workspace).

from https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by sanket1729** [comment] 2023-01-14 22:40
>  think we need to depend on bitcoin_hashes with git dep and a commit in the past first, then merge secp256k1 PR that depends on the new bitcoin_hashes and finally another PR that depends on the new bitcoin_hashes and new secp256k1.

Nevermind, I just realized multiple problems with the above solutions. This will still result in the breakage that you mention. Whenever we update bitcoin_hashes, rust-secp will break. I don't see a good way to fix this apart from the one you mentioned here.

**Comment by tcharding** [comment] 2023-01-18 22:10
I've been reading this issue every few days to see what comes out of my brain. The problem is the `patch` dependency, right? We should, as you say @Kixunil, depend on a fixed version of `hashes` not on master. Perhaps a solution ties in with our recent pre-release discussion, do a pre-release of `hashes` and depend on that. Then

1. Merge breaking change into `hashes`, do another pre-release
2. Add support to secp for `1.`, depend on latest pre-release of `hashes` - do pre-release of `secp`
3. Add support to bitcoin for `1.` and depend on latest pre-release of `hashes` and `secp`

In order that we get `1.` right perhaps it would be good enough to provide links to two branches (one on secp and one on bitcoin) that include the changes in `2.` and `3.` - then someone has to locally test and ACK?

**Comment by Kixunil** [comment] 2023-01-19 18:58
Unfortunately it's not that easy. We can no longer remove the patch without reverting some changes. So we have to depend on the older version as step 0.

**Comment by tcharding** [comment] 2023-01-19 22:45
Am I understanding your comment correctly, you suggest:
0. Do pre-release of `hashes` and depend on that instead of using the `patch` dependency as we currently do.

I'm asking because it says that in words above just not in the actual list

> do a pre-release of hashes and depend on that. Then

Or am I misunderstanding you?

**Comment by Kixunil** [comment] 2023-01-20 12:25
Correct. That being said, doing all these pre-releases seems quite an overhead.

**Comment by apoelstra** [comment] 2023-01-20 14:32
We *could* move rust-secp into this repo and have a gentleman's agreement that people aren't allowed to merge stuff into the secp tree unless one of "the crypto people" has ACKed it. Though I'm really not thrilled with sharing a PR/issues list between rust-secp and rust-bitcoin, because as I said above, rust-secp development is much slower and has a different character and it'd be overwhelmed by the rust-bitcoin activity.

I think @elichai is a maintainer of rust-secp but not of rust-bitcoin, so we'd need to promote him to also be a rust-bitcoin maintainer.

**Comment by Kixunil** [comment] 2023-01-20 19:36
We could use tags for components (we probably already should) and I have no problem with promoting @elichai 

Either way is not great. Maybe there's some more Github magic we don't know about to solve this all. Rust-lang uses a bot to manage merges so that could be a way but we would have to find an existing general-purpose bot since I don't expect anyone of us wants to write it.

**Comment by elichai** [comment] 2023-01-20 20:14
I'm also not thrilled on merging secp and bitcoin for the reasons @apoelstra laid out.

Can the "semver trick" be used for this maybe? (https://github.com/dtolnay/semver-trick) I won't be near a computer this weekend so hard for me to check

**Comment by tcharding** [comment] 2023-01-20 23:04
I think there is a misunderstanding in the stated issue

> It appeared that by merging bitcoin_hashes and patching we could do changes into multiple crates.

In my mind we merged `bitcoin_hashes` because it was maintained by the same hackers as `rust-bitcoin` so it reduced the maintenance burden to have it in with `bitcoin`. The use of `patch` was, and is IMO, a temporary hack to try and get things working quickly while we do crate smashing. We just need to get `hashes` into a "stable" state and do a release then this problem goes away.

BTW that semver trick is neat, I did not know about that.

**Comment by tcharding** [comment] 2023-01-20 23:21
And the whole problem is the hex stuff, lets just get it sorted already. I noticed this which is super nice: https://github.com/rust-bitcoin/rust-secp256k1/pull/573

**Comment by Kixunil** [comment] 2023-01-22 15:06
@elichai I don't think semver trick can help here. It's intended for released crates but we're dealing with unreleased crates and are also solving a very different problem.

> The use of `patch` was, and is IMO, a temporary hack to try and get things working quickly while we do crate smashing.

I don't think it was a hack but a rather clear solution that I'd like to keep if we can. The limitation arises from having a "hole" between dependencies.

> And the whole problem is the hex stuff,

Not really, splitting the trait uncovered the problem.

**Comment by tcharding** [comment] 2023-01-22 22:56
> > The use of `patch` was, and is IMO, a temporary hack to try and get things working quickly while we do crate smashing.
> 
> I don't think it was a hack but a rather clear solution that I'd like to keep if we can. The limitation arises from having a "hole" between dependencies.

Am I understanding correctly, there are only two known solutions
1. Merge secp into this repo (we don't want to do that)
2. Stop using `patch` dependency

**Comment by Kixunil** [comment] 2023-01-23 10:04
I think there might be a way to use `patch` differently.

**Comment by klebz** [comment] 2023-01-23 19:12
anybody down to video call?  I have some information which may help this circumatance along

**Comment by tcharding** [comment] 2023-01-28 23:46
I've come up with a working solution, please review and see if you can find any holes in the following. The set up requires 3 PRs the last must merge after the firsnt 2.

- https://github.com/rust-bitcoin/rust-bitcoin/pull/1598
- https://github.com/rust-bitcoin/rust-secp256k1/pull/575
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1599

I've tested this set up with a breaking change to `hashes`  in #1577

**Comment by apoelstra** [comment] 2023-01-30 16:53
I think there's maybe an easier strategy:

1. PR to rust-secp to update it for the breaking changes to `bitcoin_hashes`. This PR won't pass so don't merge it yet.
2. PR to rust-bitcoin with (a) the breaking changes, (b) a temporary patch to rust-secp pointing to its PR branch.
3. Release `bitcoin_hashes`
4. Update the rust-secp PR to use the new `bitcoin_hashes` release; bump rust-secp's major version; merge this and release it.
5. PR to rust-bitcoin removing the temporary patch.

**Comment by tcharding** [comment] 2023-01-30 20:43
That's hot, you legend! If we had after-work drinks I'd buy you a beer.

**Comment by Kixunil** [comment] 2023-01-31 06:10
That works but if we want to repeat this for multiple changes it'll be a bit annoying. How about we do steps 3-5 only when releasing a new version of `bitcoin`? The `secp256k1` branch may have to be rebased a few times but should be less work.

**Comment by tcharding** [comment] 2023-01-31 09:20
I hit a snag. The secp PR in `1` still has to build because of the dependency introduced in `2`. In order to get it to build I had to use a branch with the changes to `hashes` on it. Then when I did the bitcoin PR the `hashes` dependency in `bitcoin` had to be the same as the one in `secp` which, wait for it, had to be the branch _not_ the path dependency even though we are on that branch - ouch. So the bitcoin PR has a git/branch dependency in, if we merge that we will then need another series of ordered PRs into secp and bitcoin.

**Comment by tcharding** [comment] 2023-01-31 09:20
See
- https://github.com/rust-bitcoin/rust-secp256k1/pull/577
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1577

**Comment by apoelstra** [comment] 2023-01-31 13:50
@tcharding I don't think the PR in `1` needs to build on its own. Only when used as a patch in rust-bitcoin.

In step `4` we replace the PR with one that builds (or we could just close it and replace it, actually).

@Kixunil good idea.

**Comment by tcharding** [comment] 2023-01-31 20:53
> I don't think the PR in 1 needs to build on its own. Only when used as a patch in rust-bitcoin.

That's what I mean, rephrasing, when we try to build rust-bitcoin it picks up the branch in PR 1, which then gets included in the build and has to build.

Or are we both saying the same thing :)

**Comment by apoelstra** [comment] 2023-01-31 21:19
>which then gets included in the build and has to build.

but when it gets included in the build, shouldn't the `path = "./hashes"` patch line take effect so that it works?

**Comment by tcharding** [comment] 2023-02-01 03:45
It does not because `path = "./hashes"` only applies to dependencies pulled from crates.io but the secp PR is now pulling its dependency from github.

**Comment by tcharding** [comment] 2023-02-01 03:47
hmmm, trying to write that comment above clearly made me think.
```
[patch.crates-io.bitcoin_hashes]
path = "hashes"
```

Maybe there another way to use `patch` - I'll investigate.

**Comment by apoelstra** [comment] 2023-02-01 13:29
> It doesn't in this case because `path = "./hashes"` only applies to dependencies pulled from crates.io but the secp PR is now pulling its dependency from github.

The secp PR should not be pulling its dependency from github.

**Comment by sanket1729** [comment] 2023-03-24 08:19
I suppose we have to live this issue forever?

**Comment by apoelstra** [comment] 2023-03-24 12:46
I think we can close it. We found a way to deal with it last time which was a bit ugly (involved adding tags to rust-secp) but worked.

**Closed by apoelstra** 2023-03-24 12:46 UTC
Labels: P-high, brainstorm
