### ISSUE TITLE
Errors while making commits.

### ISSUE THREAD

**Issue by 15IITian** [rust-bitcoin/rust-bitcoin#2639] opened 2024-03-28 07:17 UTC
I am getting these errors while making commits as shown -> 
![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/133089376/2b350156-5a9d-463c-87c1-a55c367b912e)

![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/133089376/34f2f45a-bcea-4211-b5ff-3bcc62512a00)

Is anyone  facing same issue ?

**Comment by apoelstra** [comment] 2024-03-28 13:29
This is https://github.com/rust-lang/rust-clippy/pull/12486. You need to update or downgrade your nightly compiler.

**Comment by 15IITian** [comment] 2024-03-29 07:24
I used both the latest version `rustc 1.79.0-nightly (c9f8f3438 2024-03-27)`
and  an older version  `rustc 1.77.0-nightly (7ffc697ce 2024-01-24)` version -> but still it is not solved.

**Comment by apoelstra** [comment] 2024-03-29 14:09
The lint was merged on Feb 29. If you are really using a 01-24 nightly then you are not getting this error.

**Comment by 15IITian** [comment] 2024-03-29 16:50
I used `rustc 1.77.0-nightly (7ffc697ce 2024-01-24)` version as shown ->
![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/133089376/738d13c5-2bc6-44f2-b95d-15863a916c1a)
but error persists.

and The given pr was merged a week ago not Feb29 so this error should not come for the latest version `rustc 1.79.0-nightly (c9f8f3438 2024-03-27)`
![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/133089376/fbd68018-0c0a-45b0-8961-e8bcf57c2fce)
but no improvement.

**Comment by sanket1729** [comment] 2024-03-29 23:22
@15IITian if you are facing issues, disable the hook for now

**Comment by y21** [comment] 2024-04-04 21:57
>  The given pr was merged a week ago not Feb29 so this error should not come for the latest version rustc 1.79.0-nightly (c9f8f3438 2024-03-27)

note that we only synchronize the `rust-lang/rust-clippy` repository with the clippy submodule in the `rust-lang/rust` repo every two weeks (and all components are built from the rust repo), so the fix is not on latest nightly yet.

However, there is an open PR for a sync, so once that's merged, the next day's nightly will have it. That will likely be the 6th april

**Comment by tcharding** [comment] 2024-04-05 00:10
Thanks for the explanation @y21, I was wondering why it wasn't in nightly yet.

**Comment by y21** [comment] 2024-04-06 12:20
This should be fixed in today's nightly. Can anyone confirm this? I tried to replicate the code in the screenshot in the original post and it indeed doesn't warn anymore: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ba474a94b6f43bc9fb9206aa69ef41de

**Comment by apoelstra** [comment] 2024-04-06 13:35
Nice :) we'll see if it's confirmed when the next automatic nightly update PR comes around.

**Comment by 15IITian** [comment] 2024-04-06 13:36
Well , I just checked it out and it now  works fine .

**Comment by 15IITian** [comment] 2024-04-06 13:46
Though we have this error which is due to deprecation of legacy methods that's not any issue ->
![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/133089376/4fd181e8-f5f7-43d0-b670-5816e6b6be5a)

**Comment by apoelstra** [comment] 2024-04-06 17:19
Oh, nice, yeah, we should fix that one. (PRs are welcome, or else I'll probably do it Monday or Tuesday.)

**Comment by apoelstra** [comment] 2024-04-06 17:40
According to [the clippy msrvs.rs file](https://github.com/rust-lang/rust-clippy/blob/master/clippy_config/src/msrvs.rs) (which seems like a pretty useful file as a reference doc, though it's not always totally accurate) the new `u16::MAX` etc constants have been around since 1.43. And if we use them we don't need to do `use core::u16` etc.

**Closed** 2024-04-07 15:15 UTC

**Comment by tcharding** [comment] 2024-04-07 19:18
Yeah I removed them once we bumbed MSRV at some stage but these ones must have crept back in.
