### ISSUE TITLE
feat: faker-like functionality for txs, psbts, blocks, descriptors, etc

### ISSUE THREAD

**Issue by matthiasdebernardini** [rust-bitcoin/rust-bitcoin#2065] opened 2023-09-12 21:59 UTC
Sometimes, when I am trying to get something to work with this crate, I have to satisfy the type system to get it to compile and see some result. 

More often than not, I am interested in what rust-bitcoin is doing, rather than the data it is operating on.

Fox example, to make a random Transaction, a fair amount of code is involved (shown below in `make_rnd_tx`).

@realeinherjar and I agree that a [faker-like](https://crates.io/crates/faker_rand) set of functions in the crate would be useful for testing and app development.

Is there any appetite to add this to the crate? This could also be its own crate, I have no issue with that, though I think having the IDE autocomplete these functions would be more useful for new devs.

```rust
fn make_rnd_tx() -> Transaction {
    // Generate random 32-byte hash and 4-byte index
    let mut rng = rand::thread_rng();
    let random_bytes: [u8; 32] = rng.gen();
    let random_index: u32 = rng.gen();

    // Create OutPoint
    let out_point = OutPoint {
        txid: Txid::all_zeros(),
        vout: random_index,
    };

    // Create TxIn
    let tx_in = TxIn {
        previous_output: out_point,
        script_sig: vec![].into(),
        sequence: Sequence(Sequence::ZERO.into()),
        witness: Witness::new(),
    };

    // Create TxOut with random value
    let random_value: u64 = rng.gen_range(1..1_000_000);
    let address = Address::from_str("1P3GQYtcWgZHrrJhUa4ctoQ3QoCU2F65nz").expect("from blockchain");
    let secp = Secp256k1::new();
    let sk = SecretKey::new(&mut rand::thread_rng());
    let pk = PublicKey::new(sk.public_key(secp));
    let wpkh = pk.wpubkey_hash().expect("key is compressed");
    let script_buf = ScriptBuf::new_v0_p2wpkh(&wpkh);
    let tx_out = TxOut {
        value: random_value,
        script_pubkey: script_buf,
    };

    // Create Transaction
    Transaction {
        version: 1,
        lock_time: LockTime::Blocks(
            Height::ZERO,
        ),
        input: vec![tx_in],
        output: vec![tx_out],
    }
}

```

**Comment by junderw** [comment] 2023-09-12 22:54
We could basically do something like [this](https://docs.rs/rand/latest/rand/distributions/struct.Standard.html#custom-implementations) for a bunch of types when the rand feature is enabled.

```rust
use rand::Rng;
use rand::distributions::{Distribution, Standard};

impl Distribution<Transaction> for Standard {
    fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> Transaction {

        // .......

        Transaction {
            version: 1,
            lock_time: LockTime::Blocks(
                Height::ZERO,
            ),
            input: vec![tx_in],
            output: vec![tx_out],
        }
    }
}
```

**Comment by tcharding** [comment] 2023-09-13 09:29
Oh I like this! Would remove a lot of hex parsing in unit tests. We could put all the `Standard` imlps in separate modules/files and gate them on `#[cfg(test)]`. We should also be careful to only use public constructors so we maintain any invariants even in the random data.

**Comment by tcharding** [comment] 2023-09-13 09:31
A hard test dependency on `rand` might be a bit hard to stomach although we already have it transiently through secp and "rand-std" usage in the examples.

**Comment by matthiasdebernardini** [comment] 2023-09-13 13:54
@tcharding I'm happy to give this a shot with `Transaction`, so just add an implementation for `Standard` in here https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/blockdata/transaction.rs and put `#[cfg(test)]` above it?

**Comment by apoelstra** [comment] 2023-09-13 14:32
We definitely can't have a hard test dependency on `rand`. I'm not sure that we really need `rand` though; we could accept a random seed and then just use a sha2-based RNG or something. And when `rand` is available provide a function which randomly generates the seed.

For unit tests we'd use a fixed seed, at least initially.

**Comment by junderw** [comment] 2023-09-13 22:22
This is something I wrote on another project based on a paper that proposed a 128 bit PRNG.

Maybe something like this would help. (See: [Xorshift](https://en.wikipedia.org/wiki/Xorshift))

```rust
struct Xorshift128(u32, u32, u32, u32);

impl Xorshift128 {
    fn new(seed: u32) -> Self {
        // Initial state is first 128 bits of
        // secp256k1 generator point x value
        Xorshift128(
            0x79BE_667E ^ seed,
            0xF9DC_BBAC ^ seed.wrapping_shl(13),
            0x55A0_6295 ^ seed.wrapping_shr(7),
            0xCE87_0B07 ^ seed.wrapping_shl(5),
        )
    }

    fn next_32bytes(&mut self) -> [u8; 32] {
        let ret = [0_u32; 8].map(|_| self.next_u32());
        // We know this is safe
        unsafe { core::mem::transmute::<[u32; 8], [u8; 32]>(ret) }
    }

    fn next_u32(&mut self) -> u32 {
        /* Algorithm "xor128" from p. 5 of Marsaglia, "Xorshift RNGs" */
        let mut t = self.3;

        let s = self.0; /* Perform a contrived 32-bit shift. */
        self.3 = self.2;
        self.2 = self.1;
        self.1 = s;

        t ^= t.wrapping_shl(11);
        t ^= t.wrapping_shr(8);
        self.0 = t ^ s ^ s.wrapping_shr(19);
        self.0
    }
}
```

**Comment by matthiasdebernardini** [comment] 2023-10-08 17:06
@junderw thanks for the suggestion, I didn't need `next_32bytes` so I took it out.

This is what I have so far, is this something that could be merged? 

```
    /// Generates a random transaction for the purpose of testing
    pub fn get_random_transaction() -> Transaction {
        struct Xorshift128(u32, u32, u32, u32);

        impl Xorshift128 {
            fn new(seed: u32) -> Self {
                // Initial state is first 128 bits of
                // secp256k1 generator point x value
                Xorshift128(
                    0x79BE_667E ^ seed,
                    0xF9DC_BBAC ^ seed.wrapping_shl(13),
                    0x55A0_6295 ^ seed.wrapping_shr(7),
                    0xCE87_0B07 ^ seed.wrapping_shl(5),
                )
            }

            fn next_u32(&mut self) -> u32 {
                /* Algorithm "xor128" from p. 5 of Marsaglia, "Xorshift RNGs" */
                let mut t = self.3;

                let s = self.0; /* Perform a contrived 32-bit shift. */
                self.3 = self.2;
                self.2 = self.1;
                self.1 = s;

                t ^= t.wrapping_shl(11);
                t ^= t.wrapping_shr(8);
                self.0 = t ^ s ^ s.wrapping_shr(19);
                self.0
            }
        }

        let mut random_bytes = [0u8; 32];
        for (i, seed) in (0..32).enumerate() {
            let secp = Secp256k1::new();
            random_bytes[i] = Xorshift128::new(seed).next_u32() as u8;
        }
        // let random_bytes: [u8; 32] = (0..32).into_iter().map(|seed| Xorshift128::new(seed).next_u32() as u8).collect::<Vec<u8>>()[0..32];
        let random_index: u32 = Xorshift128::new(1).next_u32();

        // Create OutPoint
        let out_point = OutPoint {
            txid: Txid::all_zeros(),
            vout: random_index,
        };

        // Create TxIn
        let tx_in = TxIn {
            previous_output: out_point,
            script_sig: vec![].into(),
            sequence: Sequence(Sequence::ZERO.into()),
            witness: Witness::new(),
        };

        // Create TxOut with random value
        let random_value: u64 = ((Xorshift128::new(2).next_u32() as u64) % 1_000_000 as u64) as u64;
        let secp : Secp256k1<_> = Secp256k1::new();

        let sk = SecretKey::from_slice(&[
            0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
            0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFE,
            0xBA, 0xAE, 0xDC, 0xE6, 0xAF, 0x48, 0xA0, 0x3B,
            0xBF, 0xD2, 0x5E, 0x8C, 0xD0, 0x36, 0x41, 0x40,
        ]).expect("taken from tests");

        let pk = PublicKey::new(sk.public_key(&secp));
        let wpkh = pk.wpubkey_hash().expect("key is compressed");
        let script_buf = ScriptBuf::new_p2wpkh(&wpkh);
        let value: Amount = Amount::from_sat(random_value);
        let tx_out = TxOut {
            value,
            script_pubkey: script_buf,
        };

        // Create Transaction
        Transaction {
            version: Version(1),
            lock_time: LockTime::Blocks(
                Height::ZERO,
            ),
            input: vec![tx_in],
            output: vec![tx_out],
        }
    }
```

**Comment by apoelstra** [comment] 2023-10-08 17:23
@matthiasdebernardini the RNG looks good to me, though we'd want an API that lets you produce arbitrary objects, not just u32s. We could use the same API to produce random u64s, random amounts, random keypairs, random spks, etc.

For each object we'd also want a particular skewed distribution that caused edge cases to be more prominent. For example, with versions we'd choose uniformly from {1, 2, u32::max, 0, {uniform distribution on u32}}.

Your code to produce a random transaction looks too "manual" to me.

**Comment by matthiasdebernardini** [comment] 2023-10-08 17:31
Thank you for the prompt feedback! 

Where should this struct and impl block go? 

What should I name it? I propose 'PovertyRand' or something to that effect to discourage use. 

Should it be its own PR?

**Comment by apoelstra** [comment] 2023-10-08 19:38
@matthiasdebernardini I think `TestRand` would be sufficient to discourage use.

I think it ought to go somewhere in bitcoin-internals, so it can be used by all the other crates. Annoyingly this means we can't simply `cfg(test)`-gate it. Nor, I think, can we put it behind some sort of test-only feature.

**Comment by Kixunil** [comment] 2024-01-27 19:10
Could this be satisfied simply by implementing `Arbitrary` from `bolero`? If yes this is effectively a dupe of #1370

**Comment by apoelstra** [comment] 2024-01-28 13:50
Yes, that's my understanding. Thanks for noticing this old issue.

**Closed by apoelstra** 2024-01-28 13:50 UTC

**Comment by matthiasdebernardini** [comment] 2024-01-29 19:00
@Kixunil thank you for adding your input, can you share how you would go about using `bolero` and `Arbitrary` to create a random transaction? 

I'm glad this already exists because I was unsure how to implement this feature so that it "fits" into rust-bitcoin. 

I was also using psbt_faker (python tool from Coinkite devs).

**Comment by Kixunil** [comment] 2024-01-29 22:10
It's not yet implemented but we want to - hence why this is considered a duplicate. When it's ready simply writing `let transaction = bolero::gen::<Transaction>();` will do the trick.

But now I'm wondering, do you need that transaction to be consensus-valid?

**Comment by matthiasdebernardini** [comment] 2024-01-29 22:35
> But now I'm wondering, do you need that transaction to be consensus-valid?

Not necessarily, but say I did, would there be any issues?

Thanks, for the reply.

**Comment by Kixunil** [comment] 2024-01-29 22:47
Normally `Transaction` doesn't guarantee validity so it'd be awkward. And for testing robustness, many applications will actually want invalid transaction. `bolero` also doesn't support specifying multiple strategies (I think) so the only solution would be using a newtype.

So it's nice that you don't need it (yet).

**Comment by camshaft** [comment] 2024-02-01 21:10
> bolero also doesn't support specifying multiple strategies

The current implementation of `derive(TypeGenerator)` doesn't create a parameterized generator for you. But there's 
https://docs.rs/bolero-generator/latest/bolero_generator/trait.TypeGeneratorWithParams.html that you can implement to allow you to do things like

```rust
gen::<Vec<u8>>().with().len(1..6)
```

**Comment by Kixunil** [comment] 2024-02-02 09:40
I'm not sure how one would implement something like `gen::<Transaction>().with().valid()` but it's cool that there's presumably support for it.
