### ISSUE TITLE
Building with serde feature fails

### ISSUE THREAD

**Issue by canndrew** [rust-bitcoin/rust-bitcoin#372] opened 2019-12-23 08:55 UTC
Both 0.21.0 (the latest published version) and master fail to build when `features = ["serde"]` is specified. On master, the error is:

```
error[E0463]: can't find crate for `hex`
  --> src/lib.rs:59:38
   |
59 | #[cfg(any(test, feature = "serde"))] extern crate hex;
   |                                      ^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `bitcoin`.

To learn more, run the command again with --verbose.
```

**Comment by dr-orlovsky** [comment] 2019-12-23 09:45
This will be probably fixed with PR #349 merge - I had this error during my initial work on the hash types and later I was able to get rid of it.

**Comment by elichai** [comment] 2019-12-23 10:20
You need to use `features = ["use-serde"]` not `serde`. (as cargo doesn't allow to collide package names with feature names. so by using `serde` you enable the package serde but not the feature `use-serde` we should probably make it such that passing `serde` doesn't really do anything codewise)

**Comment by apoelstra** [comment] 2019-12-23 18:34
It's kinda weird that we have `extern crate hex` gated on the `serde` feature and not the `hex` feature ... but if #349 fixes it I guess we shouldn't touch it for now.

**Comment by canndrew** [comment] 2019-12-26 04:08
Thanks y'all. I figured out I had to use `use-serde` instead of serde. This should probably be mentioned in the crate-level docs though, so I'm leaving this open for now.

**Comment by dr-orlovsky** [comment] 2020-01-08 15:51
Once #349 is merged and new version is published, @canndrew, can you pls re-check is the issue is still present?

**Comment by elichai** [comment] 2020-01-08 18:06
> Once #349 is merged and new version is published, @canndrew, can you pls re-check is the issue is still present?

A. It won't change anything because of #381.
B. Even with #381 you're going to see **a lot** of weird errors[0], especially in macros. the crate isn't built to be used with the `serde` feature, only with the `use-serde` feature.

[0] https://gist.github.com/elichai/0702bf777c47d71b65ac1c8a5f4b46d7

**Closed** 2021-01-11 19:28 UTC
