### ISSUE TITLE
`tx.get_size()`?

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/rust-bitcoin#266] opened 2019-05-24 05:54 UTC
There is `tx.get_weight()` - any reason why there's no `get_size`?

**Comment by TheBlueMatt** [comment] 2019-05-24 13:45
Because size isn't used for anything anymore? I mean happy to add it but it's unused at a protocol level now.

**Comment by dpc** [comment] 2019-05-24 15:57
Some apps might need it for legacy purposes, so it would still be beneficial to have it. Maybe behind some inconvenient name `get_legacy_size` or whatever.

**Comment by stevenroose** [comment] 2019-06-06 09:27
@dpc do you mean the entire serialization size with witness data, then?

It would not be more efficient than just serializing, right? Perhaps a `consensus::Encodable::encode_len` provided method that just serializes and returns the size would make sense so you can do the same for blocks.

**Comment by dpc** [comment] 2019-06-06 16:18
@stevenroose (I think) I mean the serialization without the witness - like the pre-segwit nodes would see/count the size. I'm working on Bitcoin Indexer, and would be useful for me to display `size`, just like a lot of existing explorers show it even if just to compare. Having some blanket `encode_len` might be useful too, though this one is actually easy to achieve by just serializing (eg. into a `Write`er that discards writes, and just keeps track of the sum).

**Comment by apoelstra** [comment] 2019-06-15 17:46
After #265 you'll be able to just encode into a dummy encoder to get the encoded length.

**Comment by apoelstra** [comment] 2019-06-15 17:47
Oh, yeah, and you can currently do this with a "dummy" encoder that also records lengths.

As for `get_legacy_size` which also drops the witnesses, I think that's worthwhile to have as it's hard to get elsewhere and has some real-world meaning.

**Comment by dr-orlovsky** [comment] 2019-12-01 09:47
It seems that the issue is closed by https://github.com/rust-bitcoin/rust-bitcoin/pull/265?

**Comment by apoelstra** [comment] 2019-12-01 14:42
I don't think so, since #265 doesn't easily let you serialize without witnesses, which you need to do in order to get the legacy tx size.

**Comment by dr-orlovsky** [comment] 2019-12-01 14:49
Ok, I can implement it as a `get_legacy_size`. Also I was thinking about writing `Tx::get_fee` function, which I need, for instance, in doing some commitment protocols on top of rust-bitcoin

**Comment by dr-orlovsky** [comment] 2019-12-02 03:18
fee is implemented in #354

**Comment by elichai** [comment] 2020-03-29 14:51
@dpc Can I close this now? https://github.com/rust-bitcoin/rust-bitcoin/pull/416

**Closed** 2020-03-30 15:31 UTC
