### ISSUE TITLE
Method to calculate `PartiallySignedTransaction` fee

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#1220] opened 2022-08-30 18:34 UTC
It can be done manually, but it would be nice if there was a method to calculate a transaction's fee. Perhaps `tx.fee()` or `tx.calculate_fee()`.

**Comment by Kixunil** [comment] 2022-08-30 18:39
Impossible because `Transaction` would have to know previous outputs. It could be done on PSBT or with additional argument supplying previous outputs. In either case it'd would still return `Option`/Result` if previous outputs are not found.

**Comment by Kixunil** [comment] 2022-08-30 18:54
Yep, this is useful for payjoin as well. So in a way duplicate of #630

**Comment by apoelstra** [comment] 2022-08-30 19:35
Good to have a specific issue about this.

**Closed** 2022-10-24 23:32 UTC
Labels: enhancement, good first issue
